export const StaticRoutes = {
  home: "/",
  signin: "/signin",
  signup: "/signup",
  aboutUs: "/about-us",
  contactUs: "/contact-us",
  wishlist: "/wishlist",
  cart: "/cart",
  profile: "/profile",
  orders: "/orders",
  checkout: "/checkout",
  product: "/product/:id",
  terms: "/terms",
  thankYou: "/thankYou",
  notFound: "/not-found",
};
