export const StaticApi = {
  signin: "/authentication/loginUser",
  signup: "/authentication/createNewUser",

  getAllProductCategory: "/productcategory/getAllProductCategory",
  getAllActivateProduct: "/product/getActiveProductVariants",
  getRelatedProduct: "/product/same-category",
  getProductByProductCode: "/product/getProductByProductCode",
  searchProducts: "/product/searchProduct",
  addWishlist: "/wishlist/addWishlist",
  removeFromWishlist: "/wishlist/remove",
  getUserWishlist: "/wishlist/getUserWishlist",
  removeFromCart: "/cart/removeFromCart",
  removeSingleItemCart: "/cart/removeFromCart",
  removeProductFromCart: "/cart/remove-variant",
  addToCart: "/cart/addToCart",
  getUserCart: "/cart/getCartItemsOfUser",
  getAllAddressesOfUser: "/user/address/getAllAddressesOfUser",
  createAddress: "/user/address/createAddress",
  updateAddress: "/user/address/updateAddress",
  deleteAddress: "/user/address/deleteAddress",
  setDefaultAddress: "/user/address/setDefaultAddress",
  placeOrder: "/order/place-cart-order",
  getMyOrders: "/order/user-orders",
  directOrder: "/order/direct-order",
  cancelOrder: "/order/cancelOrder",
  getOrderById: "/order/getOrderById/:id",
};
